config_name = 'bs9_concrete_cnn_score_net_auxiliary'

[dataset]
path_kilogram = './kilogram/dataset/'
path_concrete_images = './images/'
input_image_type = 'concrete'
# Method used to increase contrast. Recommend 'normalize'.
# Options: 'normalize', 'equalize_hist'
method_increase_contrast = 'equalize_hist'
# Method used to conduct binarization. Recommend 'otsu'.
# Options: 'otsu'
method_binarization = 'otsu'

[score_net]
num_fc_layers = 4
hidden_dim = 64
embed_dim = 32
checkpoint = 'score_net_v1.3.1_corrected.pt'

[cnn_backbone]
model = 'SimpleCNN'
batch_norm = true
cnn_structure = [64, 64, 'M', 128, 128, 'M', 256, 256, 'M']
checkpoint = ''

[segmentation_model]
model_type = 'vit_h'
checkpoint = 'sam_vit_h_4b8939.pth'

[training]
learning_rate = 0.0002
num_epochs = 20000
batch_size = 45
t_max = 0.05
t_decay = false
cnn_auxiliary = true
