config_name = 'bs9_simple_cnn_6_layers_no_pretrain_concrete_input'

[dataset]
path_kilogram = './kilogram/dataset/'
path_concrete_images = './images/'
input_image_type = 'concrete'

[score_net]
num_fc_layers = 4
hidden_dim = 64
embed_dim = 32
checkpoint = ''

[cnn_backbone]
model = 'SimpleCNN'
batch_norm = true
cnn_structure = [64, 64, 'M', 128, 128, 'M', 256, 256, 'M']
checkpoint = ''

[segmentation_model]
model_type = 'vit_h'
checkpoint = 'sam_vit_h_4b8939.pth'

[training]
learning_rate = 0.0002
num_epochs = 500000
batch_size = 36
t_max = 0.05
t_decay = false
